name: 更新map

on:
  push:
    branches: ["master"]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 安装python3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: 运行map.py
        run: |
          python map.py
      - name: 设置git邮箱和姓名
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
      - name: 合并分支
        run: |
          git merge
      - name: 推送
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: "Actions: 更新map.md"
          branch: master
